# This file defines the services, networks, and volumes for  Docker application.
# It allow us to run a multi-container Docker application with a single command.

version: '3.8' # Specifies the Docker Compose file format version. Using '3.8' for modern features.

services: # Defines the services (containers) that make up  application.
  web:
    build: # Specifies how to build the Docker image for this service.
      context: . # The build context is the current directory (project root),
      dockerfile: ./nginx/Dockerfile.nginx 
    container_name: network-systemadmin-app 
    ports: 
      - "80:80" # Maps port 80 on the host (where Docker Compose is running)
    restart: always 