# ansible/deploy_app.yml
---
- name: Deploy Dockerized Nginx Static App
  hosts: web_servers
  become: yes # Needed to manage Docker daemon

  vars:
    # Docker image and container names
    docker_image_name: "mohibulhasan/network-systemadmin-ca-01-web"
    docker_image_tag: "1.0"
    docker_container_name: "my-nginx-app"
    # Ensuring this maps port 80 on the VM to port 80 in the container
    host_port: 80
    container_port: 80

  tasks:
    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: pull
        state: present # Ensures the image is present and pulls if needed

    - name: Stop and remove old container if it exists
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: absent
        force_kill: yes # Ensure it's removed if it's stuck

    - name: Run new Docker container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}:1.0"
        state: started # Ensure container is running
        recreate: yes # Always recreate to get new image/config
        ports:
          - "{{ host_port }}:{{ container_port }}" # Map host port to container port
        # If your Nginx serves from /usr/share/nginx/html, this isn't strictly needed
        # volumes:
        #   - /path/on/vm/for/html:/usr/share/nginx/html
        restart_policy: always # Ensure it restarts on reboot/crash
