# ansible/install_docker.yml
---
- name: Configure and Install Docker on Ubuntu VM
  hosts: web_servers # Targets the hosts defined in the [web_servers] group in inventory.ini
  become: yes # Run tasks with sudo/root privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache for 1 hour

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip # Needed for docker Python library
          - virtualenv
          - python3-setuptools
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Compose (as standalone binary)
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64" # Check for latest version
        dest: /usr/local/bin/docker-compose
        mode: "0755"
        force: yes # Overwrite if it exists

    - name: Ensure docker-compose is executable
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Wait for Docker service to be available (sometimes needed after group change)
      pause:
        minutes: 1 # Give it a moment to apply group changes

    - name: Verify Docker installation
      command: docker --version
