---
- name: Deploy Dockerized Nginx Static App with Docker Compose to EC2
  hosts: webservers # <--- CORRECTED: Changed from 'web_servers' to 'webservers' to match your main.yml inventory
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    app_project_dir: /opt/network-systemadmin-app

  tasks:
    - name: Update all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Docker.io package
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add 'ubuntu' user to the 'docker' group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Compose (v1) via apt
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Create application project directory on EC2
      ansible.builtin.file:
        path: "{{ app_project_dir }}"
        state: directory
        mode: "0755"
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Copy entire project context to EC2 for Docker Compose build
      ansible.builtin.synchronize:
        src: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/Network-SystemAdmin-CA-01/" # This path should now be correct
        dest: "{{ app_project_dir }}/"
        mode: push
        archive: yes
        rsync_opts:
          - "--exclude=.git/"
          - "--exclude=DeployTools/"
          - "--exclude=.vscode/"
          - "--exclude=__pycache__/"
          - "--exclude=*.swp"
          - "--exclude=*.bak"

    # --- KEEP DEBUGGING TASKS FOR NOW ---
    - name: Verify copied files on EC2 (After synchronize)
      ansible.builtin.command: ls -la {{ app_project_dir }}
      register: ls_output_after_copy
    - name: Display contents of app directory on EC2 (After synchronize)
      ansible.builtin.debug:
        var: ls_output_after_copy.stdout_lines
    # --- END DEBUGGING TASKS ---

    - name: Ensure correct ownership for copied project files
      ansible.builtin.file:
        path: "{{ app_project_dir }}"
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        recurse: yes

    - name: Stop and remove old Docker Compose services (if any)
      ansible.builtin.command: |
        docker-compose down -v
      args:
        chdir: "{{ app_project_dir }}"
      ignore_errors: yes

    - name: Build and run Docker Compose services
      ansible.builtin.command: |
        docker-compose up -d --build --force-recreate
      args:
        chdir: "{{ app_project_dir }}"
      register: docker_compose_output
      changed_when: "docker_compose_output.rc == 0 and ('Creating' in docker_compose_output.stdout or 'Recreating' in docker_compose_output.stdout or 'Building' in docker_compose_output.stdout)"

    - name: Display Docker Compose deployment output
      ansible.builtin.debug:
        var: docker_compose_output.stdout_lines
