---
- name: Deploy Dockerized Nginx Static App with Docker Compose to EC2
  hosts: webservers # <--- CONFIRMED: Matches your main.yml inventory group [webservers]
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    app_project_dir: /opt/network-systemadmin-app

  tasks:
    - name: Update all apt packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Docker.io package
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add 'ubuntu' user to the 'docker' group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Compose (v1) via apt
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Create application project directory on EC2
      ansible.builtin.file:
        path: "{{ app_project_dir }}"
        state: directory
        mode: "0755"
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Copy entire project context to EC2 for Docker Compose build
      ansible.builtin.synchronize:
        # CRITICAL FIX: With 'path: .' in checkout, GITHUB_WORKSPACE is now the repo root.
        src: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/" # <--- UPDATED src path
        dest: "{{ app_project_dir }}/"
        mode: push
        archive: yes
        rsync_opts:
          - "--exclude=.git/"
          - "--exclude=DeployTools/" # Ensure this still correctly excludes the DeployTools folder
          - "--exclude=.vscode/"
          - "--exclude=__pycache__/"
          - "--exclude=*.swp"
          - "--exclude=*.bak"

    # --- REMOVE DEBUGGING TASKS (Delete these tasks) ---
    # Delete the "Debug: Display GITHUB_WORKSPACE environment variable",
    # "Debug: List contents of GITHUB_WORKSPACE", and
    # "Debug: List contents of expected repo root (if exists)" tasks.
    # --- END DEBUGGING TASKS ---

    - name: Ensure correct ownership for copied project files
      ansible.builtin.file:
        path: "{{ app_project_dir }}"
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        recurse: yes

    - name: Stop and remove old Docker Compose services (if any)
      ansible.builtin.command: |
        docker-compose down -v
      args:
        chdir: "{{ app_project_dir }}"
      ignore_errors: yes

    - name: Build and run Docker Compose services
      ansible.builtin.command: |
        docker-compose up -d --build --force-recreate
      args:
        chdir: "{{ app_project_dir }}"
      register: docker_compose_output
      changed_when: "docker_compose_output.rc == 0 and ('Creating' in docker_compose_output.stdout or 'Recreating' in docker_compose_output.stdout or 'Building' in docker_compose_output.stdout)"

    - name: Display Docker Compose deployment output
      ansible.builtin.debug:
        var: docker_compose_output.stdout_lines
